"""Stable operation kinds used by creation application requests."""

from __future__ import annotations

from enum import Enum


class OperationKind(str, Enum):
    """Logical operation identity included in canonical request digests."""

    CREATE_CHAPTER_TASK = "CREATE_CHAPTER_TASK"
    TRANSITION_CHAPTER_TASK = "TRANSITION_CHAPTER_TASK"
    CREATE_AUTHOR_DECISION = "CREATE_AUTHOR_DECISION"
    CONSUME_AUTHOR_DECISION = "CONSUME_AUTHOR_DECISION"
    PREPARE_CANON_CHANGESET = "PREPARE_CANON_CHANGESET"
    APPROVE_CANON_CHANGESET = "APPROVE_CANON_CHANGESET"
    APPLY_CANON_COMMIT = "APPLY_CANON_COMMIT"
    RECOVER_CANON_COMMIT = "RECOVER_CANON_COMMIT"
    SUBMIT_AUTHORING_ARTIFACT = "SUBMIT_AUTHORING_ARTIFACT"
    SUBMIT_DRAFT_FOR_REVIEW = "SUBMIT_DRAFT_FOR_REVIEW"
    PREPARE_PLAN_FOR_APPROVAL = "PREPARE_PLAN_FOR_APPROVAL"
