"""Single-chapter creation domain protocol."""

from .hashing import (
    CreationDomainError,
    InvalidContentHash,
    InvalidDomainValue,
    canonicalize_json_value,
    compute_content_hash,
    verify_content_hash,
)
from .models import (
    SCHEMA_VERSION,
    ArtifactRef,
    AuditEvent,
    AuthorDecision,
    ChapterBeat,
    ChapterPlan,
    ChapterTask,
    ChapterTaskStatus,
    CreativeIntent,
    DecisionOutcome,
    DecisionType,
    DraftKind,
    DraftRevision,
    RecoveryInfo,
    ReviewFinding,
    ReviewReport,
    ReviewSeverity,
    ReviewVerdict,
    SourceKind,
    SourceRef,
)
from .state_machine import (
    InvalidAuthorDecision,
    InvalidStateTransition,
    RevisionConflict,
    can_transition,
    transition_task,
    validate_author_decision,
)

__all__ = [
    "SCHEMA_VERSION",
    "ArtifactRef",
    "AuditEvent",
    "AuthorDecision",
    "ChapterBeat",
    "ChapterPlan",
    "ChapterTask",
    "ChapterTaskStatus",
    "CreationDomainError",
    "CreativeIntent",
    "DecisionOutcome",
    "DecisionType",
    "DraftKind",
    "DraftRevision",
    "InvalidAuthorDecision",
    "InvalidContentHash",
    "InvalidDomainValue",
    "InvalidStateTransition",
    "RecoveryInfo",
    "ReviewFinding",
    "ReviewReport",
    "ReviewSeverity",
    "ReviewVerdict",
    "RevisionConflict",
    "SourceKind",
    "SourceRef",
    "can_transition",
    "canonicalize_json_value",
    "compute_content_hash",
    "transition_task",
    "validate_author_decision",
    "verify_content_hash",
]

